channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch=2.5
  - matplotlib
  - ipykernel
  - numpy
  - scipy
  - pylint
  - mypy
  - cython
  - pip
  - scikit-image
  - tqdm
  - attrs
  - gitpython
  - nbconvert
  - tabulate
  - black
  - isort
  - absl-py
  - pip:
    - nibabel
    - fasteners
    - antspyx
    - git+https://github.com/deepmind/surface-distance.git
    - composable-mapping == 0.1.2
    - deformation-inversion-layer >= 1.1.2
    - gdown
